name: Second workflow
on: workflow_dispatch
jobs: 
  first-job:
   runs-on: ubuntu-latest
   steps:
    - name: print name
      run: echo "VishnuVardhan"
  second-job:
    runs-on: ubuntu-latest
    steps: 
      - name: prtint schoolname
        run: echo "MVM school"
      - name: print running multilinecommands
        run: | 
            echo "Pet name is Kutty"
            echo: "Age: 9"
            
        
        
    

